{
 "title": "Cross Stream Query on Bilibili Video Analysis (Video Stream, Danmaku Stream)",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "params",
    "query": "SELECT string_agg(item, '|')\nFROM\n(\n  SELECT\n    concat(scope, ' ', stream, ' ', to_char(start_time, 'YYYY-MM-DDTFMHH24:MI:SSZ'),' ', to_char(end_time, 'YYYY-MM-DDTFMHH24:MI:SSZ')) as item\n  FROM\n  (\n    SELECT scope, stream, start_time, end_time, positive_percent, negative_percent\n    FROM\n    (\n      SELECT\n          scope, stream, start_time, end_time, pos_count/CAST(count AS FLOAT) as positive_percent, neg_count/CAST(count AS FLOAT) as negative_percent\n        FROM  clip_score\n        \n    ) as clip_score2\n    \n    WHERE  ${comment_percent} ${operator} ${operator_value}\n    ORDER BY ${comment_percent} ${order_by}\n    limit 6\n  ) as clip_score3\n  \n)as clip_score4"
   },
   {
    "name": "comment_percent",
    "label": "comments",
    "query": "positive_percent, negative_percent"
   },
   { "name": "operator", "query": ">=,<=" },
   { "name": "operator_value", "query": "0.2" },
   { "name": "order_by", "label": "Order by", "query": "ASC, DESC " },
   { "name": "clip_len", "label": "Clip Length", "query": "10s" },
   { "name": "location", "label": "Comment Location", "query": "Shanghai,Chengdu,Beijing" },
   { "name": "host", "query": "http://10.247.97.51:3030" }
  ]
 },
 "panels": [
  {
   "title": "Introduction",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "This dashboard demonstrates the use case of Cross Stream Query between the video stream and the Danmaku stream. (For more information of Danmaku, go to https://en.wikipedia.org/wiki/Danmaku)\nThe the data is collected from a Chinese video sharing website: bilibili.com (Only the data collected on China mainland)\n\nFeatures not valid yet: the comment location filter on the top bar. \n"
   }
  },
  {
   "title": "video component",
   "type": "pravegavideoplayer-panel",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__time(time_column),\n  value1\nFROM\n  metric_table\nWHERE\n  $__timeFilter(time_column)\n"
    }
   ]
  },
  {
   "title": "Distribution of clip likes",
   "type": "histogram",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count\r\nFROM  clip_score"
    }
   ]
  },
  {
   "title": "Comments sentiment analysis",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  SUM(pos_count)AS positive, SUM(neg_count)AS negative, SUM(count - pos_count - neg_count) as neutral\r\nFROM  clip_score\r\n"
    }
   ]
  },
  {
   "title": "Comments count by location",
   "type": "geomap",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT\n  province, gross as comment, lat, lon\nFROM\n  province\n\n"
    }
   ]
  }
 ]
}