apiVersion: v1
kind: Service
metadata:
  name: adminer
  annotations:
    nautilus.dellemc.com/http-ingress: http
    nautilus.dellemc.com/http-ingress-name: adminer
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  selector:
    release: adminer
  type: ClusterIP
