apiVersion: v1
kind: Service
metadata:
  name: video-server
  annotations:
    nautilus.dellemc.com/http-ingress: http
    nautilus.dellemc.com/http-ingress-name: pravega-video-server
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: http-web-svc
  selector:
    release: pravega-video-server
  type: ClusterIP
